M48
; DRILL file {KiCad 7.0.11+dfsg-1build4} date lun 16 mar 2026 11:24:30
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-16T11:24:30-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+dfsg-1build4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
%
G90
G05
T1
X102.362Y-102.362
X102.362Y-107.638
X107.638Y-102.362
M30
